version: '3'

services:
  db:
    image: 'mysql:latest'
    ports:
           - "3307:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=root
           - MYSQL_DATABASE=tpachato
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    restart: always
  backend:
    image: 'oussemabelaid7/devops:latest'
    ports:
           - "8089:8089"
    links:
           - "db"
    depends_on:
           - "db"
    restart: on-failure
